package cn.aorise.sample.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.aorise.sample.db.entity.SampleNote;

import cn.aorise.sample.db.SampleNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sampleNoteDaoConfig;

    private final SampleNoteDao sampleNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sampleNoteDaoConfig = daoConfigMap.get(SampleNoteDao.class).clone();
        sampleNoteDaoConfig.initIdentityScope(type);

        sampleNoteDao = new SampleNoteDao(sampleNoteDaoConfig, this);

        registerDao(SampleNote.class, sampleNoteDao);
    }
    
    public void clear() {
        sampleNoteDaoConfig.clearIdentityScope();
    }

    public SampleNoteDao getSampleNoteDao() {
        return sampleNoteDao;
    }

}
