package cn.aorise.hospital.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.aorise.hospital.db.entity.HospitalNote;

import cn.aorise.hospital.db.HospitalNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hospitalNoteDaoConfig;

    private final HospitalNoteDao hospitalNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hospitalNoteDaoConfig = daoConfigMap.get(HospitalNoteDao.class).clone();
        hospitalNoteDaoConfig.initIdentityScope(type);

        hospitalNoteDao = new HospitalNoteDao(hospitalNoteDaoConfig, this);

        registerDao(HospitalNote.class, hospitalNoteDao);
    }
    
    public void clear() {
        hospitalNoteDaoConfig.clearIdentityScope();
    }

    public HospitalNoteDao getHospitalNoteDao() {
        return hospitalNoteDao;
    }

}
