package com.product.masktime.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TBL_FACIAL_MASK_DIARY_DATA.
 */
public class TblFacialMaskDiaryData {

    private Long id;
    /** Not-null value. */
    private String DiaryDate;
    private String DiaryTime;
    private String PicName;
    private String DiaryContent;
    private String QuestionId;
    private String DiaryTitle;
    private String CloudFlag;
    private String Fill;
    private String UpdateTime;

    public TblFacialMaskDiaryData() {
    }

    public TblFacialMaskDiaryData(Long id) {
        this.id = id;
    }

    public TblFacialMaskDiaryData(Long id, String DiaryDate, String DiaryTime, String PicName, String DiaryContent, String QuestionId, String DiaryTitle, String CloudFlag, String Fill, String UpdateTime) {
        this.id = id;
        this.DiaryDate = DiaryDate;
        this.DiaryTime = DiaryTime;
        this.PicName = PicName;
        this.DiaryContent = DiaryContent;
        this.QuestionId = QuestionId;
        this.DiaryTitle = DiaryTitle;
        this.CloudFlag = CloudFlag;
        this.Fill = Fill;
        this.UpdateTime = UpdateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDiaryDate() {
        return DiaryDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDiaryDate(String DiaryDate) {
        this.DiaryDate = DiaryDate;
    }

    public String getDiaryTime() {
        return DiaryTime;
    }

    public void setDiaryTime(String DiaryTime) {
        this.DiaryTime = DiaryTime;
    }

    public String getPicName() {
        return PicName;
    }

    public void setPicName(String PicName) {
        this.PicName = PicName;
    }

    public String getDiaryContent() {
        return DiaryContent;
    }

    public void setDiaryContent(String DiaryContent) {
        this.DiaryContent = DiaryContent;
    }

    public String getQuestionId() {
        return QuestionId;
    }

    public void setQuestionId(String QuestionId) {
        this.QuestionId = QuestionId;
    }

    public String getDiaryTitle() {
        return DiaryTitle;
    }

    public void setDiaryTitle(String DiaryTitle) {
        this.DiaryTitle = DiaryTitle;
    }

    public String getCloudFlag() {
        return CloudFlag;
    }

    public void setCloudFlag(String CloudFlag) {
        this.CloudFlag = CloudFlag;
    }

    public String getFill() {
        return Fill;
    }

    public void setFill(String Fill) {
        this.Fill = Fill;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

}
